services:
  postgres:
    image: postgres:15
    container_name: oauth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oauth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oauth-network

  oauth-backend:
    build: .
    container_name: oauth-backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=oauth_db
      - JWT_SECRET=4QunkBgO9v2HaKq34qnnXBkv49HHkCSL
      - PORT=3000
      - NODE_ENV=production
      - GOOGLE_CLIENT_ID=379548023802-gco09cs45q0j44vpqe7c59e4pg3lnph0.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=http://45.77.38.239.nip.io:3000/auth/google/callback
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - oauth-network

volumes:
  postgres_data:

networks:
  oauth-network:
    driver: bridge
